version: 0.0
os: linux
files:
  - source: /
    destination: /var/apps/mymoney
hooks:
  AfterInstall:
    - location: scripts/run_migration.sh
      timeout: 300
      runas: mymoney
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: mymoney
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: mymoney
