# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 170a15e7ef030682a47baba1207cb67587b27fbf05622e6345501702c301d683d6f0a4c18d4bbc718c1098970a3abbd4730e2fd66760232946eff5a086a0aae6

test:
  secret_key_base: 63b6fa2c033b534a169c5b81546d360f2595f12221e67900a8261e166d0eaea9342459e0e12c56d8e2253bc22766b095507a263de2a2529c8e1e7501f3a4b6fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
